import React, { Component } from 'react';
import _ from 'lodash'
import ReactDOM from 'react-dom';
import SearchBar from './components/search_bar';
import YTSearch from 'youtube-api-search';
import VideoList from './components/vide_list'
import VideoDetail from './components/video_detail'

const API_KEY = 'AIzaSyCn3EqZjPQnLNApsJ3_dmmh12CKkqI2Mek';


//create components .this will create html;

class App extends Component {
    constructor(props) {
        super(props);
        this.state = { 
            videos: [],
            selectedVideo:null
        };
        this.videoSearch('blockchain')
    }
    videoSearch(term){
        YTSearch({ key: API_KEY, term }, videos => {
            this.setState({
                videos,
                selectedVideo:videos[0]
            });
        })
    }
    render() {
        const videoSearch = _.debounce((term)=>{this.videoSearch(term)},300)
        return (
            <div>
                <SearchBar onSearchTerm={videoSearch}/>
                <VideoDetail video={this.state.selectedVideo}/>
                <VideoList 
                onVideoSelect={(selectedVideo) =>this.setState({selectedVideo})}
                videos ={this.state.videos}/>
            </div>
        );
    }
}

//take these html generated by components and
//put in the page (DOM)
ReactDOM.render(<App />, document.querySelector('.container'))